ssl:
    build: "./"
    volumes_from:
        - data
    environment:
        CA: "/usr/local/etc/ssl/ca/root.ca"
        DNS_0: example.localhost
        DNS_1: example.localhost.de
        DNS_2: example.localhost.at
        DNS_3: example.localhost.ch
data:
    build: "./"
    entrypoint: "/bin/true"
