ssl:
    build: "./"
    volumes_from:
        - data
    environment:
        CA: "/usr/local/etc/ssl/ca/root.ca"
        DNS_0: spectra.localhost
        DNS_1: spectra.localhost.de
        DNS_2: spectra.localhost.at
        DNS_3: spectra.localhost.ch
data:
    build: "./"
    entrypoint: "/bin/true"
